theme = "onedark"

[editor]
line-number = "relative"
bufferline = "multiple"
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.normal]
"A-j" = "goto_next_paragraph"
"A-k" = "goto_prev_paragraph"

[keys.select]
"A-j" = "goto_next_paragraph"
"A-k" = "goto_prev_paragraph"
